name: openvpn_flutter_example
description: Demonstrates how to use the openvpn_flutter plugin. 
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  openvpn_flutter: ^1.3.4
  cupertino_icons: ^1.0.2
  connectivity_plus: ^6.1.4
  flutter_screenutil: ^5.9.3
  http: ^1.3.0
  csv: ^6.0.0
  google_maps_flutter: ^2.12.1
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^9.1.0
  get_it: ^7.6.6
  intl: ^0.19.0
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  custom_marker_builder: ^0.0.3+1
  auto_size_text: ^3.0.0
  uicons_pro: ^1.1.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^1.0.0
  very_good_analysis: ^6.0.0
 
flutter: 
  uses-material-design: true
  assets:
    - assets/animations/